---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: weboaks/node-karma-protractor-chrome
    tag: "latest"

inputs:
- name: codebase

run:
  path: ./codebase/ci/tasks/run-e2e.sh
