---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalpa/angular-cli

inputs:
- name: codebase

outputs:
- name: compiled-code

run:
  path: ./codebase/ci/tasks/run-build.sh
