resources:
- name: codebase
  type: git
  source:
    uri: https://github.com/mgiannamore/angular-testing
    branch: master
- name: cloud-foundry-bazaz-demo
  type: cf
  source:
    api: https://api.sys.gn01.pcf.dcsg.com
    username: ((cf_user_nonprod))
    password: ((cf_password_nonprod))
    organization: bazaz-demo
    space: dev
    skip_cert_check: true

jobs:
- name: run-tests
  serial: true
  plan:
  - get: codebase
    trigger: true
  - task: run-unit-tests
    file: codebase/ci/tasks/run-tests.yml
    privileged: true
  - task: run-e2e-tests
    file: codebase/ci/tasks/run-e2e.yml
    privileged: true
- name: build-and-deploy
  serial: true
  plan:
    - get: codebase
      trigger: true
      passed:
      - run-tests
    - task: run-build
      file: codebase/ci/tasks/run-build.yml
    - put: cloud-foundry-bazaz-demo
      params:
        manifest: codebase/manifest.yml
        path: compiled-code/
