resources:
- name: codebase
  type: git
  source:
    uri: https://github.com/mgiannamore/angular-testing
    branch: master

jobs:
- name: unit-test
  serial: true
  plan:
  - get: codebase
    trigger: true
  - task: run-tests
    file: codebase/ci/tasks/run-tests.yml
    privileged: true
- name: build-and-deploy
  serial: true
  plan:
    - get: codebase
      trigger: true
      passed:
      - unit-test
    - task: run-build
      file: codebase/ci/tasks/run-build.yml
